// Donnees de test pour le developpement - MUTE App
import { Artist, Venue, Concert } from '../types';

export const mockArtists: Artist[] = [
  // Artistes francais
  {
    id: 'artist-1',
    name: 'Phoenix',
    imageUrl: 'https://picsum.photos/seed/phoenix/400/400',
    genres: ['Rock', 'Indie'],
    popularity: 85,
    description: 'Groupe de rock francais forme a Versailles en 1999.',
  },
  {
    id: 'artist-2',
    name: 'Christine and the Queens',
    imageUrl: 'https://picsum.photos/seed/christine/400/400',
    genres: ['Pop', 'Electronic'],
    popularity: 82,
    description: 'Projet musical de Heloise Letissier.',
  },
  {
    id: 'artist-3',
    name: 'Justice',
    imageUrl: 'https://picsum.photos/seed/justice/400/400',
    genres: ['Electronic', 'Techno'],
    popularity: 88,
    description: 'Duo francais de musique electronique.',
  },
  {
    id: 'artist-4',
    name: 'Disclosure',
    imageUrl: 'https://picsum.photos/seed/disclosure/400/400',
    genres: ['Electronic', 'House'],
    popularity: 80,
    description: 'Duo britannique de musique electronique.',
  },
  {
    id: 'artist-5',
    name: 'Arctic Monkeys',
    imageUrl: 'https://picsum.photos/seed/arctic/400/400',
    genres: ['Rock', 'Indie'],
    popularity: 92,
    description: 'Groupe de rock britannique forme a Sheffield.',
  },
  {
    id: 'artist-6',
    name: 'Aya Nakamura',
    imageUrl: 'https://picsum.photos/seed/aya/400/400',
    genres: ['Pop', 'R&B'],
    popularity: 90,
    description: 'Chanteuse et compositrice francaise.',
  },
  {
    id: 'artist-7',
    name: 'Parcels',
    imageUrl: 'https://picsum.photos/seed/parcels/400/400',
    genres: ['Disco', 'Funk'],
    popularity: 75,
    description: 'Groupe australien base a Berlin.',
  },
  {
    id: 'artist-8',
    name: 'Orelsan',
    imageUrl: 'https://picsum.photos/seed/orelsan/400/400',
    genres: ['Hip-Hop', 'Rap'],
    popularity: 88,
    description: 'Rappeur et realisateur francais.',
  },
  {
    id: 'artist-9',
    name: 'Amelie Lens',
    imageUrl: 'https://picsum.photos/seed/amelie/400/400',
    genres: ['Techno'],
    popularity: 85,
    description: 'DJ et productrice belge de techno.',
  },
  {
    id: 'artist-10',
    name: 'Charlotte de Witte',
    imageUrl: 'https://picsum.photos/seed/charlotte/400/400',
    genres: ['Techno'],
    popularity: 87,
    description: 'DJ et productrice belge.',
  },
  {
    id: 'artist-11',
    name: 'Folamour',
    imageUrl: 'https://picsum.photos/seed/folamour/400/400',
    genres: ['House', 'Disco'],
    popularity: 78,
    description: 'DJ et producteur francais de house.',
  },
  {
    id: 'artist-12',
    name: 'Myd',
    imageUrl: 'https://picsum.photos/seed/myd/400/400',
    genres: ['Electronic', 'House'],
    popularity: 72,
    description: 'Producteur francais, membre de Club Cheval.',
  },
  {
    id: 'artist-13',
    name: 'Vladimir Cauchemar',
    imageUrl: 'https://picsum.photos/seed/vladimir/400/400',
    genres: ['Electronic', 'Hip-Hop'],
    popularity: 70,
    description: 'Producteur et DJ francais masque.',
  },
  {
    id: 'artist-14',
    name: 'Polo & Pan',
    imageUrl: 'https://picsum.photos/seed/polopan/400/400',
    genres: ['Electronic', 'House'],
    popularity: 82,
    description: 'Duo francais de musique electronique.',
  },
  {
    id: 'artist-15',
    name: 'Louisahhh',
    imageUrl: 'https://picsum.photos/seed/louisahhh/400/400',
    genres: ['Techno'],
    popularity: 75,
    description: 'DJ et productrice americaine basee a Paris.',
  },
  // Nouveaux artistes
  {
    id: 'artist-16',
    name: 'Angele',
    imageUrl: 'https://picsum.photos/seed/angele/400/400',
    genres: ['Pop', 'R&B'],
    popularity: 91,
    description: 'Chanteuse et musicienne belge.',
  },
  {
    id: 'artist-17',
    name: 'Stromae',
    imageUrl: 'https://picsum.photos/seed/stromae/400/400',
    genres: ['Electronic', 'Hip-Hop'],
    popularity: 93,
    description: 'Auteur-compositeur-interprete belge.',
  },
  {
    id: 'artist-18',
    name: 'The Blaze',
    imageUrl: 'https://picsum.photos/seed/blaze/400/400',
    genres: ['Electronic', 'House'],
    popularity: 80,
    description: 'Duo francais de musique electronique.',
  },
  {
    id: 'artist-19',
    name: 'Vald',
    imageUrl: 'https://picsum.photos/seed/vald/400/400',
    genres: ['Hip-Hop', 'Rap'],
    popularity: 84,
    description: 'Rappeur francais.',
  },
  {
    id: 'artist-20',
    name: 'Nekfeu',
    imageUrl: 'https://picsum.photos/seed/nekfeu/400/400',
    genres: ['Hip-Hop', 'Rap'],
    popularity: 86,
    description: 'Rappeur francais membre de S-Crew et 1995.',
  },
  {
    id: 'artist-21',
    name: 'Hamza',
    imageUrl: 'https://picsum.photos/seed/hamza/400/400',
    genres: ['Hip-Hop', 'R&B'],
    popularity: 79,
    description: 'Rappeur et chanteur belge.',
  },
  {
    id: 'artist-22',
    name: 'Clara Luciani',
    imageUrl: 'https://picsum.photos/seed/clara/400/400',
    genres: ['Pop', 'Chanson'],
    popularity: 83,
    description: 'Auteure-compositrice-interprete francaise.',
  },
  {
    id: 'artist-23',
    name: 'Lomepal',
    imageUrl: 'https://picsum.photos/seed/lomepal/400/400',
    genres: ['Hip-Hop', 'Rap'],
    popularity: 81,
    description: 'Rappeur et skateur francais.',
  },
  {
    id: 'artist-24',
    name: 'Woodkid',
    imageUrl: 'https://picsum.photos/seed/woodkid/400/400',
    genres: ['Electronic', 'Orchestral'],
    popularity: 77,
    description: 'Compositeur et realisateur francais.',
  },
  {
    id: 'artist-25',
    name: 'Flavien Berger',
    imageUrl: 'https://picsum.photos/seed/flavien/400/400',
    genres: ['Electronic', 'Pop'],
    popularity: 68,
    description: 'Musicien et compositeur francais.',
  },
  {
    id: 'artist-26',
    name: 'Yseult',
    imageUrl: 'https://picsum.photos/seed/yseult/400/400',
    genres: ['R&B', 'Soul'],
    popularity: 74,
    description: 'Chanteuse francaise.',
  },
  {
    id: 'artist-27',
    name: 'Pomme',
    imageUrl: 'https://picsum.photos/seed/pomme/400/400',
    genres: ['Pop', 'Folk'],
    popularity: 76,
    description: 'Auteure-compositrice-interprete francaise.',
  },
  {
    id: 'artist-28',
    name: 'Ben Bohmer',
    imageUrl: 'https://picsum.photos/seed/benbohmer/400/400',
    genres: ['Electronic', 'Deep House'],
    popularity: 73,
    description: 'DJ et producteur allemand.',
  },
  {
    id: 'artist-29',
    name: 'Nina Kraviz',
    imageUrl: 'https://picsum.photos/seed/nina/400/400',
    genres: ['Techno'],
    popularity: 84,
    description: 'DJ et productrice russe.',
  },
  {
    id: 'artist-30',
    name: 'Jeff Mills',
    imageUrl: 'https://picsum.photos/seed/jeffmills/400/400',
    genres: ['Techno'],
    popularity: 82,
    description: 'DJ et producteur americain, pionnier de la techno de Detroit.',
  },
  {
    id: 'artist-31',
    name: 'Bicep',
    imageUrl: 'https://picsum.photos/seed/bicep/400/400',
    genres: ['Electronic', 'House'],
    popularity: 79,
    description: 'Duo de producteurs nord-irlandais.',
  },
  {
    id: 'artist-32',
    name: 'Moderat',
    imageUrl: 'https://picsum.photos/seed/moderat/400/400',
    genres: ['Electronic', 'IDM'],
    popularity: 78,
    description: 'Supergroupe allemand de musique electronique.',
  },
  {
    id: 'artist-33',
    name: 'Bonobo',
    imageUrl: 'https://picsum.photos/seed/bonobo/400/400',
    genres: ['Electronic', 'Downtempo'],
    popularity: 80,
    description: 'Musicien et producteur britannique.',
  },
  {
    id: 'artist-34',
    name: 'Jamie xx',
    imageUrl: 'https://picsum.photos/seed/jamiexx/400/400',
    genres: ['Electronic', 'House'],
    popularity: 81,
    description: 'Producteur britannique, membre de The xx.',
  },
  {
    id: 'artist-35',
    name: 'Four Tet',
    imageUrl: 'https://picsum.photos/seed/fourtet/400/400',
    genres: ['Electronic', 'IDM'],
    popularity: 77,
    description: 'Producteur britannique de musique electronique.',
  },
  {
    id: 'artist-36',
    name: 'Floating Points',
    imageUrl: 'https://picsum.photos/seed/floating/400/400',
    genres: ['Electronic', 'Jazz'],
    popularity: 74,
    description: 'DJ et producteur britannique.',
  },
  {
    id: 'artist-37',
    name: 'Roi Heenok',
    imageUrl: 'https://picsum.photos/seed/heenok/400/400',
    genres: ['Hip-Hop', 'Rap'],
    popularity: 65,
    description: 'Rappeur franco-congolais.',
  },
  {
    id: 'artist-38',
    name: 'Laylow',
    imageUrl: 'https://picsum.photos/seed/laylow/400/400',
    genres: ['Hip-Hop', 'R&B'],
    popularity: 78,
    description: 'Rappeur et producteur francais.',
  },
  {
    id: 'artist-39',
    name: 'SDM',
    imageUrl: 'https://picsum.photos/seed/sdm/400/400',
    genres: ['Hip-Hop', 'Rap'],
    popularity: 76,
    description: 'Rappeur francais.',
  },
  {
    id: 'artist-40',
    name: 'Josman',
    imageUrl: 'https://picsum.photos/seed/josman/400/400',
    genres: ['Hip-Hop', 'Rap'],
    popularity: 77,
    description: 'Rappeur francais.',
  },
  {
    id: 'artist-41',
    name: 'Izzy la Push',
    imageUrl: 'https://picsum.photos/seed/izzy/400/400',
    genres: ['Pop', 'R&B'],
    popularity: 62,
    description: 'Chanteur francais.',
  },
  {
    id: 'artist-42',
    name: 'Lous and the Yakuza',
    imageUrl: 'https://picsum.photos/seed/lous/400/400',
    genres: ['Pop', 'R&B'],
    popularity: 73,
    description: 'Chanteuse belgo-congolaise.',
  },
  {
    id: 'artist-43',
    name: 'Bon Entendeur',
    imageUrl: 'https://picsum.photos/seed/bonentendeur/400/400',
    genres: ['Electronic', 'House'],
    popularity: 71,
    description: 'Collectif francais de musique electronique.',
  },
  {
    id: 'artist-44',
    name: 'L\'Imperatrice',
    imageUrl: 'https://picsum.photos/seed/imperatrice/400/400',
    genres: ['Disco', 'Pop'],
    popularity: 75,
    description: 'Groupe francais de synth-pop.',
  },
  {
    id: 'artist-45',
    name: 'Tame Impala',
    imageUrl: 'https://picsum.photos/seed/tameimpala/400/400',
    genres: ['Rock', 'Psychedelic'],
    popularity: 88,
    description: 'Projet musical australien de Kevin Parker.',
  },
  {
    id: 'artist-46',
    name: 'Kungs',
    imageUrl: 'https://picsum.photos/seed/kungs/400/400',
    genres: ['Electronic', 'House'],
    popularity: 79,
    description: 'DJ et producteur francais.',
  },
  {
    id: 'artist-47',
    name: 'DJ Snake',
    imageUrl: 'https://picsum.photos/seed/djsnake/400/400',
    genres: ['Electronic', 'EDM'],
    popularity: 89,
    description: 'DJ et producteur francais.',
  },
  {
    id: 'artist-48',
    name: 'David Guetta',
    imageUrl: 'https://picsum.photos/seed/guetta/400/400',
    genres: ['Electronic', 'EDM'],
    popularity: 94,
    description: 'DJ et producteur francais.',
  },
  {
    id: 'artist-49',
    name: 'Petit Biscuit',
    imageUrl: 'https://picsum.photos/seed/petitbiscuit/400/400',
    genres: ['Electronic', 'Chill'],
    popularity: 76,
    description: 'Producteur francais de musique electronique.',
  },
  {
    id: 'artist-50',
    name: 'Sofiane Pamart',
    imageUrl: 'https://picsum.photos/seed/sofiane/400/400',
    genres: ['Classical', 'Piano'],
    popularity: 72,
    description: 'Pianiste et compositeur francais.',
  },
];

export const mockVenues: Venue[] = [
  {
    id: 'venue-1',
    name: 'Olympia',
    address: '28 Boulevard des Capucines',
    city: 'Paris',
    postalCode: '75009',
    arrondissement: '9e',
    latitude: 48.8701,
    longitude: 2.3280,
    capacity: 2000,
    imageUrl: 'https://picsum.photos/seed/olympia/600/400',
  },
  {
    id: 'venue-2',
    name: 'Zenith Paris',
    address: '211 Avenue Jean Jaures',
    city: 'Paris',
    postalCode: '75019',
    arrondissement: '19e',
    latitude: 48.8936,
    longitude: 2.3934,
    capacity: 6800,
    imageUrl: 'https://picsum.photos/seed/zenith/600/400',
  },
  {
    id: 'venue-3',
    name: 'La Cigale',
    address: '120 Boulevard de Rochechouart',
    city: 'Paris',
    postalCode: '75018',
    arrondissement: '18e',
    latitude: 48.8826,
    longitude: 2.3407,
    capacity: 1400,
    imageUrl: 'https://picsum.photos/seed/cigale/600/400',
  },
  {
    id: 'venue-4',
    name: 'Bataclan',
    address: '50 Boulevard Voltaire',
    city: 'Paris',
    postalCode: '75011',
    arrondissement: '11e',
    latitude: 48.8632,
    longitude: 2.3701,
    capacity: 1500,
    imageUrl: 'https://picsum.photos/seed/bataclan/600/400',
  },
  {
    id: 'venue-5',
    name: 'Accor Arena',
    address: '8 Boulevard de Bercy',
    city: 'Paris',
    postalCode: '75012',
    arrondissement: '12e',
    latitude: 48.8386,
    longitude: 2.3787,
    capacity: 20300,
    imageUrl: 'https://picsum.photos/seed/bercy/600/400',
  },
  {
    id: 'venue-6',
    name: 'Le Trabendo',
    address: '211 Avenue Jean Jaures',
    city: 'Paris',
    postalCode: '75019',
    arrondissement: '19e',
    latitude: 48.8910,
    longitude: 2.3922,
    capacity: 700,
    imageUrl: 'https://picsum.photos/seed/trabendo/600/400',
  },
  {
    id: 'venue-7',
    name: 'La Maroquinerie',
    address: '23 Rue Boyer',
    city: 'Paris',
    postalCode: '75020',
    arrondissement: '20e',
    latitude: 48.8673,
    longitude: 2.3918,
    capacity: 500,
    imageUrl: 'https://picsum.photos/seed/maroquinerie/600/400',
  },
  {
    id: 'venue-8',
    name: 'Elysee Montmartre',
    address: '72 Boulevard de Rochechouart',
    city: 'Paris',
    postalCode: '75018',
    arrondissement: '18e',
    latitude: 48.8833,
    longitude: 2.3483,
    capacity: 1500,
    imageUrl: 'https://picsum.photos/seed/elysee/600/400',
  },
  {
    id: 'venue-9',
    name: 'Rex Club',
    address: '5 Boulevard Poissonniere',
    city: 'Paris',
    postalCode: '75002',
    arrondissement: '2e',
    latitude: 48.8710,
    longitude: 2.3477,
    capacity: 800,
    imageUrl: 'https://picsum.photos/seed/rex/600/400',
  },
  {
    id: 'venue-10',
    name: 'Concrete',
    address: '69 Port de la Rapee',
    city: 'Paris',
    postalCode: '75012',
    arrondissement: '12e',
    latitude: 48.8436,
    longitude: 2.3665,
    capacity: 600,
    imageUrl: 'https://picsum.photos/seed/concrete/600/400',
  },
  {
    id: 'venue-11',
    name: 'Badaboum',
    address: '2 bis Rue des Taillandiers',
    city: 'Paris',
    postalCode: '75011',
    arrondissement: '11e',
    latitude: 48.8532,
    longitude: 2.3771,
    capacity: 400,
    imageUrl: 'https://picsum.photos/seed/badaboum/600/400',
  },
  {
    id: 'venue-12',
    name: 'Glazart',
    address: '7-15 Avenue de la Porte de la Villette',
    city: 'Paris',
    postalCode: '75019',
    arrondissement: '19e',
    latitude: 48.8976,
    longitude: 2.3867,
    capacity: 1200,
    imageUrl: 'https://picsum.photos/seed/glazart/600/400',
  },
  {
    id: 'venue-13',
    name: 'Le Petit Bain',
    address: '7 Port de la Gare',
    city: 'Paris',
    postalCode: '75013',
    arrondissement: '13e',
    latitude: 48.8318,
    longitude: 2.3761,
    capacity: 450,
    imageUrl: 'https://picsum.photos/seed/petitbain/600/400',
  },
  {
    id: 'venue-14',
    name: 'La Machine du Moulin Rouge',
    address: '90 Boulevard de Clichy',
    city: 'Paris',
    postalCode: '75018',
    arrondissement: '18e',
    latitude: 48.8841,
    longitude: 2.3324,
    capacity: 900,
    imageUrl: 'https://picsum.photos/seed/machine/600/400',
  },
  {
    id: 'venue-15',
    name: 'Wanderlust',
    address: '32 Quai d\'Austerlitz',
    city: 'Paris',
    postalCode: '75013',
    arrondissement: '13e',
    latitude: 48.8412,
    longitude: 2.3698,
    capacity: 1500,
    imageUrl: 'https://picsum.photos/seed/wanderlust/600/400',
  },
  {
    id: 'venue-16',
    name: 'Cabaret Sauvage',
    address: '59 Boulevard MacDonald',
    city: 'Paris',
    postalCode: '75019',
    arrondissement: '19e',
    latitude: 48.8961,
    longitude: 2.3891,
    capacity: 1200,
    imageUrl: 'https://picsum.photos/seed/cabaret/600/400',
  },
  {
    id: 'venue-17',
    name: 'Casino de Paris',
    address: '16 Rue de Clichy',
    city: 'Paris',
    postalCode: '75009',
    arrondissement: '9e',
    latitude: 48.8788,
    longitude: 2.3288,
    capacity: 1600,
    imageUrl: 'https://picsum.photos/seed/casino/600/400',
  },
  {
    id: 'venue-18',
    name: 'Salle Pleyel',
    address: '252 Rue du Faubourg Saint-Honore',
    city: 'Paris',
    postalCode: '75008',
    arrondissement: '8e',
    latitude: 48.8769,
    longitude: 2.3003,
    capacity: 1913,
    imageUrl: 'https://picsum.photos/seed/pleyel/600/400',
  },
  {
    id: 'venue-19',
    name: 'Philharmonie de Paris',
    address: '221 Avenue Jean Jaures',
    city: 'Paris',
    postalCode: '75019',
    arrondissement: '19e',
    latitude: 48.8909,
    longitude: 2.3941,
    capacity: 2400,
    imageUrl: 'https://picsum.photos/seed/philharmonie/600/400',
  },
  {
    id: 'venue-20',
    name: 'La Bellevilloise',
    address: '19-21 Rue Boyer',
    city: 'Paris',
    postalCode: '75020',
    arrondissement: '20e',
    latitude: 48.8674,
    longitude: 2.3896,
    capacity: 800,
    imageUrl: 'https://picsum.photos/seed/bellevilloise/600/400',
  },
  {
    id: 'venue-21',
    name: 'Le Trianon',
    address: '80 Boulevard de Rochechouart',
    city: 'Paris',
    postalCode: '75018',
    arrondissement: '18e',
    latitude: 48.8829,
    longitude: 2.3467,
    capacity: 1100,
    imageUrl: 'https://picsum.photos/seed/trianon/600/400',
  },
  {
    id: 'venue-22',
    name: 'La Gaite Lyrique',
    address: '3 bis Rue Papin',
    city: 'Paris',
    postalCode: '75003',
    arrondissement: '3e',
    latitude: 48.8668,
    longitude: 2.3543,
    capacity: 700,
    imageUrl: 'https://picsum.photos/seed/gaite/600/400',
  },
  {
    id: 'venue-23',
    name: 'New Morning',
    address: '7-9 Rue des Petites Ecuries',
    city: 'Paris',
    postalCode: '75010',
    arrondissement: '10e',
    latitude: 48.8741,
    longitude: 2.3502,
    capacity: 500,
    imageUrl: 'https://picsum.photos/seed/newmorning/600/400',
  },
  {
    id: 'venue-24',
    name: 'Stade de France',
    address: '93216 Saint-Denis',
    city: 'Saint-Denis',
    postalCode: '93216',
    latitude: 48.9244,
    longitude: 2.3601,
    capacity: 80698,
    imageUrl: 'https://picsum.photos/seed/stadefrance/600/400',
  },
  {
    id: 'venue-25',
    name: 'La Defense Arena',
    address: '99 Jardins de l\'Arche',
    city: 'Nanterre',
    postalCode: '92000',
    latitude: 48.8956,
    longitude: 2.2299,
    capacity: 40000,
    imageUrl: 'https://picsum.photos/seed/defensearena/600/400',
  },
];

// Genere des dates realistes pour les prochaines semaines
const generateFutureDates = (): string[] => {
  const dates: string[] = [];
  const now = new Date();

  for (let i = 0; i < 60; i++) {
    const date = new Date(now);
    date.setDate(now.getDate() + i);
    dates.push(date.toISOString().split('T')[0]);
  }
  return dates;
};

const futureDates = generateFutureDates();

// Concerts de demonstration pour le mode offline ou test
// Ces donnees sont utilisees quand les APIs ne repondent pas
export const mockConcerts: Concert[] = [
  // Ce soir
  {
    id: 'mock-1',
    artist: mockArtists[2], // Justice
    venue: mockVenues[8], // Rex Club
    date: futureDates[0], // Aujourd'hui
    startTime: '23:00',
    endTime: '06:00',
    price: { min: 20, max: 25, currency: '€' },
    ticketUrl: 'https://example.com/justice',
    source: 'manual',
    sourceId: 'mock-1',
    genre: 'Electronic',
    imageUrl: 'https://picsum.photos/seed/justice-live/800/600',
    description: 'Justice en live au Rex Club - Une nuit electro legendaire',
  },
  {
    id: 'mock-2',
    artist: mockArtists[8], // Amelie Lens
    venue: mockVenues[9], // Concrete
    date: futureDates[0],
    startTime: '23:59',
    endTime: '12:00',
    price: { min: 25, max: 30, currency: '€' },
    ticketUrl: 'https://example.com/amelie',
    source: 'manual',
    sourceId: 'mock-2',
    genre: 'Techno',
    imageUrl: 'https://picsum.photos/seed/amelie-lens/800/600',
  },
  // Demain
  {
    id: 'mock-3',
    artist: mockArtists[0], // Phoenix
    venue: mockVenues[0], // Olympia
    date: futureDates[1],
    startTime: '20:00',
    endTime: '23:00',
    price: { min: 45, max: 75, currency: '€' },
    ticketUrl: 'https://example.com/phoenix',
    source: 'manual',
    sourceId: 'mock-3',
    genre: 'Rock',
    imageUrl: 'https://picsum.photos/seed/phoenix-olympia/800/600',
    description: 'Phoenix en concert exceptionnel a l\'Olympia',
  },
  // Week-end
  {
    id: 'mock-4',
    artist: mockArtists[7], // Orelsan
    venue: mockVenues[4], // Accor Arena
    date: futureDates[3],
    startTime: '20:30',
    price: { min: 55, max: 95, currency: '€' },
    ticketUrl: 'https://example.com/orelsan',
    source: 'manual',
    sourceId: 'mock-4',
    genre: 'Hip-Hop',
    imageUrl: 'https://picsum.photos/seed/orelsan-bercy/800/600',
    description: 'Civilisation Tour - La tournee evenement',
  },
  {
    id: 'mock-5',
    artist: mockArtists[13], // Polo & Pan
    venue: mockVenues[1], // Zenith
    date: futureDates[4],
    startTime: '20:00',
    price: { min: 42, max: 55, currency: '€' },
    ticketUrl: 'https://example.com/polopan',
    source: 'manual',
    sourceId: 'mock-5',
    genre: 'Electronic',
    imageUrl: 'https://picsum.photos/seed/polopan-zenith/800/600',
  },
  {
    id: 'mock-6',
    artist: mockArtists[9], // Charlotte de Witte
    venue: mockVenues[13], // La Machine du Moulin Rouge
    date: futureDates[5],
    startTime: '23:00',
    endTime: '07:00',
    price: { min: 28, max: 35, currency: '€' },
    ticketUrl: 'https://example.com/charlotte',
    source: 'manual',
    sourceId: 'mock-6',
    genre: 'Techno',
    imageUrl: 'https://picsum.photos/seed/charlotte-machine/800/600',
  },
  // Semaine prochaine
  {
    id: 'mock-7',
    artist: mockArtists[15], // Angele
    venue: mockVenues[4], // Accor Arena
    date: futureDates[8],
    startTime: '20:00',
    price: { min: 45, max: 85, currency: '€' },
    ticketUrl: 'https://example.com/angele',
    source: 'manual',
    sourceId: 'mock-7',
    genre: 'Pop',
    imageUrl: 'https://picsum.photos/seed/angele-bercy/800/600',
    description: 'Nonante-cinq Tour - Derniere date parisienne',
  },
  {
    id: 'mock-8',
    artist: mockArtists[10], // Folamour
    venue: mockVenues[10], // Badaboum
    date: futureDates[9],
    startTime: '23:30',
    price: { min: 15, max: 20, currency: '€' },
    ticketUrl: 'https://example.com/folamour',
    source: 'manual',
    sourceId: 'mock-8',
    genre: 'House',
    imageUrl: 'https://picsum.photos/seed/folamour-badaboum/800/600',
  },
  {
    id: 'mock-9',
    artist: mockArtists[4], // Arctic Monkeys
    venue: mockVenues[24], // La Defense Arena
    date: futureDates[12],
    startTime: '20:30',
    price: { min: 55, max: 120, currency: '€' },
    ticketUrl: 'https://example.com/arcticmonkeys',
    source: 'manual',
    sourceId: 'mock-9',
    genre: 'Rock',
    imageUrl: 'https://picsum.photos/seed/arctic-arena/800/600',
    isSoldOut: true,
    description: 'The Car Tour - Complet',
  },
  {
    id: 'mock-10',
    artist: mockArtists[16], // Stromae
    venue: mockVenues[23], // Stade de France
    date: futureDates[15],
    startTime: '21:00',
    price: { min: 65, max: 150, currency: '€' },
    ticketUrl: 'https://example.com/stromae',
    source: 'manual',
    sourceId: 'mock-10',
    genre: 'Electronic',
    imageUrl: 'https://picsum.photos/seed/stromae-stade/800/600',
    description: 'Multitude Tour - Concert exceptionnel au Stade de France',
  },
  // Plus tard dans le mois
  {
    id: 'mock-11',
    artist: mockArtists[17], // The Blaze
    venue: mockVenues[1], // Zenith
    date: futureDates[20],
    startTime: '20:30',
    price: { min: 48, max: 65, currency: '€' },
    ticketUrl: 'https://example.com/theblaze',
    source: 'manual',
    sourceId: 'mock-11',
    genre: 'Electronic',
    imageUrl: 'https://picsum.photos/seed/blaze-zenith/800/600',
  },
  {
    id: 'mock-12',
    artist: mockArtists[19], // Nekfeu
    venue: mockVenues[4], // Accor Arena
    date: futureDates[22],
    startTime: '20:00',
    price: { min: 50, max: 90, currency: '€' },
    ticketUrl: 'https://example.com/nekfeu',
    source: 'manual',
    sourceId: 'mock-12',
    genre: 'Hip-Hop',
    imageUrl: 'https://picsum.photos/seed/nekfeu-bercy/800/600',
  },
  {
    id: 'mock-13',
    artist: mockArtists[28], // Nina Kraviz
    venue: mockVenues[11], // Glazart
    date: futureDates[25],
    startTime: '23:00',
    endTime: '08:00',
    price: { min: 22, max: 28, currency: '€' },
    ticketUrl: 'https://example.com/ninakraviz',
    source: 'manual',
    sourceId: 'mock-13',
    genre: 'Techno',
    imageUrl: 'https://picsum.photos/seed/nina-glazart/800/600',
  },
  {
    id: 'mock-14',
    artist: mockArtists[21], // Clara Luciani
    venue: mockVenues[0], // Olympia
    date: futureDates[28],
    startTime: '20:00',
    price: { min: 38, max: 55, currency: '€' },
    ticketUrl: 'https://example.com/claraluciani',
    source: 'manual',
    sourceId: 'mock-14',
    genre: 'Pop',
    imageUrl: 'https://picsum.photos/seed/clara-olympia/800/600',
  },
  {
    id: 'mock-15',
    artist: mockArtists[30], // Bicep
    venue: mockVenues[15], // Cabaret Sauvage
    date: futureDates[30],
    startTime: '22:00',
    price: { min: 35, max: 45, currency: '€' },
    ticketUrl: 'https://example.com/bicep',
    source: 'manual',
    sourceId: 'mock-15',
    genre: 'Electronic',
    imageUrl: 'https://picsum.photos/seed/bicep-cabaret/800/600',
  },
  // Mois prochain
  {
    id: 'mock-16',
    artist: mockArtists[46], // DJ Snake
    venue: mockVenues[24], // La Defense Arena
    date: futureDates[35],
    startTime: '21:00',
    price: { min: 55, max: 95, currency: '€' },
    ticketUrl: 'https://example.com/djsnake',
    source: 'manual',
    sourceId: 'mock-16',
    genre: 'Electronic',
    imageUrl: 'https://picsum.photos/seed/djsnake-arena/800/600',
  },
  {
    id: 'mock-17',
    artist: mockArtists[44], // Tame Impala
    venue: mockVenues[4], // Accor Arena
    date: futureDates[40],
    startTime: '20:30',
    price: { min: 52, max: 85, currency: '€' },
    ticketUrl: 'https://example.com/tameimpala',
    source: 'manual',
    sourceId: 'mock-17',
    genre: 'Rock',
    imageUrl: 'https://picsum.photos/seed/tame-bercy/800/600',
  },
  {
    id: 'mock-18',
    artist: mockArtists[32], // Moderat
    venue: mockVenues[18], // Philharmonie
    date: futureDates[45],
    startTime: '20:00',
    price: { min: 45, max: 70, currency: '€' },
    ticketUrl: 'https://example.com/moderat',
    source: 'manual',
    sourceId: 'mock-18',
    genre: 'Electronic',
    imageUrl: 'https://picsum.photos/seed/moderat-philharmonie/800/600',
    description: 'More D4TA Tour - Experience audiovisuelle unique',
  },
  {
    id: 'mock-19',
    artist: mockArtists[49], // Sofiane Pamart
    venue: mockVenues[17], // Salle Pleyel
    date: futureDates[50],
    startTime: '20:00',
    price: { min: 35, max: 65, currency: '€' },
    ticketUrl: 'https://example.com/sofianepamart',
    source: 'manual',
    sourceId: 'mock-19',
    genre: 'Classical',
    imageUrl: 'https://picsum.photos/seed/sofiane-pleyel/800/600',
  },
  {
    id: 'mock-20',
    artist: mockArtists[6], // Parcels
    venue: mockVenues[0], // Olympia
    date: futureDates[55],
    startTime: '20:00',
    price: { min: 42, max: 58, currency: '€' },
    ticketUrl: 'https://example.com/parcels',
    source: 'manual',
    sourceId: 'mock-20',
    genre: 'Disco',
    imageUrl: 'https://picsum.photos/seed/parcels-olympia/800/600',
  },
];
